version: "3.8"

services:
  redis:
    container_name: cache
    image: "redis"
    expose:
      - "${REDIS_PORT}"
  node_backend:
    container_name: rest_api
    image: "rest_api"
    build:
      context: .
    ports:
      - "${LOCAL_PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT:${PORT}
      - PGDATABASE:${PGDATABASE}
      - PGUSER:${PGUSER}
      - PGPASSWORD:${PGPASSWORD}
      - PGHOST:${PGHOST}
    depends_on:
      - node_db
      - redis 
  node_db:
    container_name: node_db
    image: "postgres:13"
    ports:
      - "${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - nps_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  nps_data: {}